### ISSUE TITLE
Could not pass event IslandDeletedEvent on island reset

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/addon-limits#7]
**Description**
```
08.02 08:36:52 [Server] ERROR Could not pass event IslandDeletedEvent to BentoBox v1.2.1
08.02 08:36:52 [Server] INFO org.bukkit.event.EventException: null
08.02 08:36:52 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:362) ~[?:?]
08.02 08:36:52 [Server] INFO at world.bentobox.bentobox.util.DeleteIslandChunks.lambda$new$0(DeleteIslandChunks.java:51) ~[?:?]
08.02 08:36:52 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
08.02 08:36:52 [Server] INFO Caused by: java.lang.NullPointerException
08.02 08:36:52 [Server] INFO at bentobox.addon.limits.listeners.BlockLimitsListener.onIslandDelete(BlockLimitsListener.java:278) ~[?:?]
08.02 08:36:52 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor391.execute(Unknown Source) ~[?:?]
08.02 08:36:52 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-513]
08.02 08:36:52 [Server] INFO ... 12 more
```

**Steps to reproduce the behavior:**
1. Reset an island

**Server Information:**

 - Database: yml
 - Limits 0.0.3

**Comment by tastybento** [comment]
Thanks!
